---

name:
    hledger-stockquotes
version:
    0.1.2.0
github:
    prikhi/hledger-stockquotes
homepage:
    https://github.com/prikhi/hledger-stockquotes#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2020 Pavan Rikhi
category:
    Finance, Console
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Generate HLedger Price Directives From Daily Stock Quotes.

description: |
    @hledger-stockquotes@ is an addon for <https://hledger.org/ hledger> that
    reads your journal file, pulls the historical stock prices for commodities,
    and writes out a new journal file containing the respective price
    directives.

    The <https://www.alphavantage.co/ AlphaVantage API> is used to fetch the
    stock quotes and you will need a
    <https://www.alphavantage.co/support/#api-key free API key> to use this
    program.

    You can install @hledger-stockquotes@ with Stack: @stack install --resolver
    nightly hledger-stockquotes@. Then run @hledger-stockquotes --help@ to see
    the usage instructions & all available options.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - aeson >= 1 && < 2
        - bytestring < 1
        - containers < 1
        - hledger-lib < 2
        - req >= 3 && < 4
        - safe >= 0.3.5 && < 1
        - scientific < 1
        - split < 1
        - text < 2
        - time < 2
        - unordered-containers < 0.3

executables:
    hledger-stockquotes:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - hledger-stockquotes
            - aeson >= 1 && < 2
            - bytestring < 1
            - cmdargs >= 0.6 && < 1
            - directory < 2
            - raw-strings-qq < 2
            - safe-exceptions
            - text < 2
            - time < 2
            - xdg-basedir < 1
            - yaml < 1

tests:
    hledger-stockquotes-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - hledger-stockquotes
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
